name: ecopull
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - contourpy=1.3.3
  - cycler=0.12.1
  - expat=2.7.1
  - fonttools=4.60.1
  - freetype=2.14.1
  - kiwisolver=1.4.9
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.4
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - munkres=1.1.4
  - ncurses=6.5
  - numpy=2.3.4
  - openjpeg=2.5.3
  - openssl=3.5.4
  - packaging=25.0
  - pillow=11.3.0
  - pip=25.2
  - pthread-stubs=0.4
  - pyparsing=3.2.5
  - python=3.13.9
  - python-dateutil=2.9.0.post0
  - python_abi=3.13
  - qhull=2020.2
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.50.2
  - tk=8.6.15
  - tornado=6.5.2
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/ecopull
